routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AuthController@login')->name('login');
Route::post('authentication', 'AuthController@authentication')->name('authentication');
Route::post('authentication-api', 'AuthController@authentication_api')->name('authentication_api');
Route::post('authentication-api-logout', 'AuthController@authentication_api_logout')->name('authentication_api_logout');

Route::middleware('auth')->group(function(){
	Route::post('logout', 'AuthController@logout')->name('logout');

	Route::get('home', 'HomeController@index')->name('home');

	Route::resource('words', 'WordsController');

	Route::get('teacher/remove/{id}', 'TeacherController@delete')->name('teacher.remove.student');
	Route::get('teacher/assign-student', 'TeacherController@create_student')->name('teacher.create_student');
	Route::post('teacher/assign-student', 'TeacherController@store_student')->name('teacher.store_student');
	Route::resource('teacher', 'TeacherController');

	Route::get('student/score/{id}', 'StudentController@api_scores')->name('student.scores');
	Route::resource('student', 'StudentController');
});

Route::get('easy', 'ChallengeController@easy')->name('challenge_easy');
Route::get('medium', 'ChallengeController@medium')->name('challenge_medium');
Route::get('hard', 'ChallengeController@hard')->name('challenge_hard');
Route::get('get-result', 'ChallengeController@getResult')->name('challenge_get_result');
Route::post('get-result', 'ChallengeController@getResult')->name('challenge_get_result_post');

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\User;
use App\Students;

class TeacherController extends Controller
{
	public function index(Request $request)
	{
		$search = '';
		$query = User::whereUserType(2);
		if($request->has('search') && $request->search != '') {
			$search = trim($request->search);
			$query = $query->where(function($query) use ($search) {
				$query->where('first_name', 'LIKE', "%$search%")->orWhere('last_name', 'LIKE', "%$search%");
			}); 
		}
		$rows = $query->orderBy('created_at', 'ASC')->paginate(50);
		$data = compact('rows', 'search');
		return view('teacher.index', $data);
	}

	public function create()
	{
		$route = route('teacher.store');
		$button_text = 'Save';
		$first_name = old('first_name');
		$last_name = old('last_name');
		$email = old('email');
		$password = old('password');
		$confirm_password = old('confirm_password');

		$data = compact('route', 'button_text', 'first_name', 'last_name', 'email', 'password', 'confirm_password');
		return view('teacher.form', $data);
	}

	public function store(Request $request)
	{
		$request->validate([
        	'first_name' => 'required',
        	'last_name' => 'required',
        	'email' => 'required|email|unique:users',
        	'password' => 'required|same:confirm_password'
		]);

		User::create([
			'first_name' => $request->first_name,
			'last_name' => $request->last_name,
			'email' => $request->email,
			'password' => bcrypt(trim($request->password)),
			'user_type' => 2,
		]);

		return redirect()->route('teacher.create')->with('success_msg', 'Teacher successfully added!');
	}

	public function edit($id)
	{
		$row = User::find($id);
		if (is_null($row)) {
			abort(404);
		}

		$route = route('teacher.update', $id);
		$button_text = 'Update';
		$first_name = $row->first_name;
		$last_name = $row->last_name;
		$email = $row->email;
		$password = '';
		$confirm_password = '';

		$data = compact('route', 'button_text', 'first_name', 'last_name', 'email', 'password', 'confirm_password');
		return view('teacher.form', $data);
	}

	public function update($id, Request $request)
	{
		$input = [
        	'first_name' => 'required',
        	'last_name' => 'required',
        	'email' => 'required|email'
		];

		$data = [
			'first_name' => $request->first_name,
			'last_name' => $request->last_name,
			'email' => $request->email
		];

		if ($request->password != '' || $request->confirm_password != '') {
			$input['password'] = 'same:confirm_password';
			$data['password'] = bcrypt(trim($request->password));
		}

		$request->validate($input);

		User::where('id', $id)->update($data);

		return redirect()->route('teacher.edit', $id)->with('success_msg', 'Teacher successfully updated!');
	}

	public function show($id, Request $request)
	{
		$search = '';
		$teacher = User::find($id);
		if (is_null($teacher)) {
			abort(404);
		}
		#dd(Auth::user()->id);
		$query = Students::with(['info'])->whereTeacherUsersId($teacher->id);

		/*if (Auth::user()->user_type != 0) {
			$query = $query->whereTeacherUsersId(Auth::user()->id);
		} else {
			$query = $query->whereTeacherUsersId($teacher->id);
		}*/
		
		if($request->has('search') && $request->search != '') {
			$search = trim($request->search);
			$query = $query->where(function($query) use ($search) {
				$query->where('first_name', 'LIKE', "%$search%")->orWhere('last_name', 'LIKE', "%$search%");
			}); 
		}
		$rows = $query->orderBy('created_at', 'ASC')->paginate(50);

		$data = compact('rows', 'teacher', 'search');
		return view('teacher.show', $data);
	}

	public function delete($id)
	{
		$student = User::find($id);
		if (is_null($student)) {
			abort(404);
		}
		$student = Students::where('student_users_id', $id)->first();
		if (is_null($student)) {
			abort(404);
		}

		Students::where('student_users_id', $student->teacer_users_id)->delete();

		return redirect()->route('teacher.show', $id)->with('success_msg', 'Teacher successfully updated!');
	}

	public function create_student()
	{
		$route = route('teacher.store_student');
		$button_text = 'Save';
		$teacher_user_id = old('teacher_user_id');
		$student_user_id = old('student_user_id');
		$student_name = old('student_name');
		$user_id = Auth::user()->id;

		$teachers = User::whereUserType(2)->orderBy('last_name', 'ASC')->get();
		#$students = User::whereUserType(1)->orderBy('last_name', 'ASC')->get();

		$students = User::whereUserType(1)->orderBy('last_name', 'ASC')->get();
		/*$students = User::whereUserType(1)->whereNotIn('id', function($query){
			$query->select('student_users_id')->from('students');
		})->orderBy('last_name', 'ASC')->get();*/

		$data = compact('route', 'button_text', 'teacher_user_id', 'student_user_id', 'student_name', 'teachers', 'students');
		return view('teacher.student-form', $data);
	}

	public function store_student(Request $request)
	{
		$request->validate([
        	'teacher_user_id' => 'required',
        	'student_user_id' => 'required|unique:students,student_users_id'
		]);
		#$count = Students::where('student_users_id', $request->student_user_id)->where('teacher_users_id', Auth::user()->id)->count();
		$count = Students::where('student_users_id', $request->student_user_id)->count();

		if ($count >  0) {
			return back()->withErrors(['Student already taken!']);
		}

		Students::create([
			'student_users_id' => $request->student_user_id,
			'teacher_users_id' => $request->teacher_user_id
		]);

		return redirect()->route('teacher.create_student')->with('success_msg', 'Student successfully added!');
	}
}

resources/views/teacher/form.blade.php
@extends('layouts.app')

@section('page-title', 'Form Teacher')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Teacher</div>

                <div class="card-body">
                    <form action="{{ $route }}" method="post" enctype="multipart/form-data">
                        @csrf()

                        <div class="results">
                            @include('partials.error-msg')
                        </div>

                        <div class="form-group row">
                            <label for="first_name" class="col-md-3 col-form-label text-md-right">First Name</label>
                            <div class="col-md-9">
                                <input id="first_name" type="text" class="form-control" name="first_name" value="{{ $first_name }}" autofocus="">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last_name" class="col-md-3 col-form-label text-md-right">Last Name</label>
                            <div class="col-md-9">
                                <input id="last_name" type="text" class="form-control" name="last_name" value="{{ $last_name }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-3 col-form-label text-md-right">E-Mail</label>
                            <div class="col-md-9">
                                <input id="email" type="email" class="form-control" name="email" value="{{ $email }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-3 col-form-label text-md-right">Password</label>
                            <div class="col-md-9">
                                <input id="password" type="password" class="form-control" name="password" value="{{ $password }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="confirm_password" class="col-md-3 col-form-label text-md-right">Confirm Password</label>
                            <div class="col-md-9">
                                <input id="confirm_password" type="password" class="form-control" name="confirm_password" value="{{ $confirm_password }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-5 offset-md-3">
                                @if($button_text != 'Save')
                                    @method('PUT')
                                @endif
                                <button type="submit" class="btn btn-primary">{{ $button_text }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/index.blade.php
@extends('layouts.app')

@section('page-title', 'Teacher`s List')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Teacher's List</div>

                <div class="card-body">

                        <div class="row ">
                            <div class="col-md-7"></div>
                            <div class="col-md-5">
                                <form action="{{ route('words.index') }}" method="get" enctype="multipart/form-data">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Search a Name" aria-label="Search a Name" aria-describedby="button-addon2" id="search" name="search" value="{{ $search }}" autofocus="">
                                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fa fa-search"></i></button>
                                    </div>
                                </form>
                            </div>
                            
                        </div>

                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th width="10%"></th>
                                <th width="35%">First Name</th>
                                <th width="35%">Last Name</th>
                                <th width="20%">E-Mail</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($rows as $row)
                            <tr>
                                <td>
                                    <a href="{{ route('teacher.edit', $row->id) }}" title="Edit"><i class="fa fa-edit fa-lg"></i></a>
                                    <a href="{{ route('teacher.show', $row->id) }}" title="Student List"><i class="fa fa-list fa-lg"></i></a>
                                </td>
                                <td>{{ $row->first_name }}</td>
                                <td>{{ $row->last_name }}</td>
                                <td>{{ $row->email }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $rows->appends(['search' => $search])->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/show.blade.php
@extends('layouts.app')

@section('page-title', (((Auth::user()->user_type == 0))? $teacher->first_name . ' ' . $teacher->last_name : 'My') . ' Student`s')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    @if(Auth::user()->user_type == 0)
                        {{ $teacher->first_name . ' ' . $teacher->last_name }} Student`s
                    @else
                        My Student`s
                    @endif
                </div>

                <div class="card-body">

                        <div class="results">
                            @include('partials.error-msg')
                        </div>

                        <div class="row ">
                            <div class="col-md-7"></div>
                            <div class="col-md-5">
                                <form action="{{ route('words.index') }}" method="get" enctype="multipart/form-data">
                                    <div class="input-group mb-3">
                                        @if(Auth::user()->user_type == 0)
                                        <a class="btn btn-outline-primary" href="{{ route('teacher.create_student') }}"><i class="fa fa-plus"></i></a>
                                        @endif
                                        <input type="text" class="form-control" placeholder="Search a Name" aria-label="Search a Name" aria-describedby="button-addon2" id="search" name="search" value="{{ $search }}" autofocus="">
                                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fa fa-search"></i></button>
                                    </div>
                                </form>
                            </div>
                            
                        </div>

                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th width="10%"></th>
                                <th width="35%">First Name</th>
                                <th width="35%">Last Name</th>
                                <th width="20%">E-Mail</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($rows as $row)
                            <tr>
                                <td>
                                    <a href="{{ route('teacher.remove.student', $row->id) }}" onclick=" return confirm('Are you sure to remove this student?')" title="Remove Student"><i class="fa fa-times fa-lg"></i></a>
                                    <a href="{{ route('student.show', $row->id) }}" title="Student Score"><i class="fa fa-list fa-lg"></i></a>
                                </td>
                                <td>{{ $row->info->first_name }}</td>
                                <td>{{ $row->info->last_name }}</td>
                                <td>{{ $row->info->email }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $rows->appends(['search' => $search])->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/student-form.blade.php
@extends('layouts.app')

@section('page-title', 'Assign Student')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Assign Student</div>

                <div class="card-body">
                    <form action="{{ $route }}" method="post" enctype="multipart/form-data">
                        @csrf()

                        <div class="results">
                            @include('partials.error-msg')
                        </div>

                        <div class="form-group row">
                            <label for="teacher_user_id" class="col-md-2 col-form-label text-md-right">Teacher</label>
                            <div class="col-md-10">
                                <select class="form-control" aria-label="Default select example" id="teacher_user_id" name="teacher_user_id">
                                    <option value="">-- Select --</option>
                                    @foreach($teachers as $teacher)
                                    <option value="{{ $teacher->id }}">{{ $teacher->last_name .', '. $teacher->first_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="student_user_id" class="col-md-2 col-form-label text-md-right">Student</label>
                            <div class="col-md-10">
                                <select class="form-control" aria-label="Default select example" id="student_user_id" name="student_user_id">
                                    <option value="">-- Select --</option>
                                    @foreach($students as $student)
                                    <option value="{{ $student->id }}">{{ $student->last_name .', '. $student->first_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-5 offset-md-2">
                                @if($button_text != 'Save')
                                    @method('PUT')
                                @endif
                                <button type="submit" class="btn btn-primary">{{ $button_text }}</button>
                                <a href="{{ route('teacher.show', Auth::user()->id) }}" class="btn btn-secondary">Back</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $('#teacher_user_id').val('{{ $teacher_user_id }}');
        $('#student_user_id').val('{{ $student_user_id }}');
    });
</script>
@endsection